general: &general
    pool_size: 20
    pool_timeout: 5

test:
    <<: *general
    adapter: mongodb
    database: openyourmind_test
    host: linus.mongohq.com
    port: 10089
    username: openyourmind_test
    password: openyourmind_test

development:
    <<: *general
    adapter: mongodb
    database: openyourmind_development
    host: linus.mongohq.com
    port: 10088
    username: openyourmind_development
    password: openyourmind_development

production:
    <<: *general
    adapter: mongodb
    database: <%=ENV['OPENSHIFT_APP_NAME']%>
    host: <%=ENV['OPENSHIFT_MONGODB_DB_HOST']%>
    port: <%=ENV['OPENSHIFT_MONGODB_DB_PORT']%>
    username: <%=ENV['OPENSHIFT_MONGODB_DB_USERNAME']%>
    password: <%=ENV['OPENSHIFT_MONGODB_DB_PASSWORD']%>

